# Generated by Django 5.2.8 on 2025-12-21 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0021_alter_banner_options_alter_favorite_options_and_more'),
        ('promotions', '0002_alter_promotion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['priority', '-created_at'], 'verbose_name': 'Mahabat', 'verbose_name_plural': 'Mahabatlar'},
        ),
        migrations.AlterField(
            model_name='promotion',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='announcements.announcement', verbose_name='Bildiriş'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Haçan goşuldy'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='frequency',
            field=models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('always', 'Always')], default='always', max_length=10, verbose_name='Ýygylygy'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Işjeň'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='photo',
            field=models.ImageField(upload_to='promotions/', verbose_name='Surat'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='priority',
            field=models.IntegerField(default=0, help_text='Pes saný ilki gökezilýär (0 = ileri tutma ýok)', verbose_name='Ileri tutma'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Haçan üýtgedildi'),
        ),
    ]
