# Generated by Django 5.2.8 on 2025-12-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Contact label (e.g., 'Support', 'Sales')", max_length=100)),
                ('phone_number', models.CharField(help_text='Phone number with country code', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this contact is visible to users')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Number',
                'verbose_name_plural': 'Contact Numbers',
                'ordering': ['order', 'label'],
            },
        ),
    ]
