# Generated by Django 5.2.8 on 2025-12-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['order', 'label'], 'verbose_name': 'Habarlaşmak belgisi', 'verbose_name_plural': 'Habarlaşmak belgileri'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Haçan goşuldy'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Bu habarlaşmak ulanyjýlara görezilýärmi', verbose_name='Işjeň'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='label',
            field=models.CharField(help_text="Habarlaşmak belliklerini girióiň (mysal: 'Goldaw', 'Satýw')", max_length=100, verbose_name='Bellik'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='order',
            field=models.IntegerField(default=0, help_text='Görkeziliş tertibi (pes sanlar ilki gökezilýär)', verbose_name='Tertip'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(help_text='Telefon belgisi ýurt kody bilen', max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Haçan üýtgedildi'),
        ),
    ]
