# Generated by Django 5.2.8 on 2025-12-21 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_tokens', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicetoken',
            options={'ordering': ['-created_at'], 'verbose_name': 'Enjam tokeni', 'verbose_name_plural': 'Enjam tokenleri'},
        ),
        migrations.AlterModelOptions(
            name='notificationlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bildiriş logsy', 'verbose_name_plural': 'Bildiriş logslary'},
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Haçan goşuldy'),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='fcm_token',
            field=models.TextField(blank=True, null=True, verbose_name='FCM Token'),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Işjeň'),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='platform',
            field=models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], default='android', max_length=20, verbose_name='Platforma'),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='token',
            field=models.CharField(max_length=255, unique=True, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Haçan üýtgedildi'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='body',
            field=models.TextField(verbose_name='Tekst'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Haçan goşuldy'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='data',
            field=models.JSONField(blank=True, null=True, verbose_name='Maglumat'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='failure_count',
            field=models.IntegerField(default=0, verbose_name='Ýetenýtmeşlemeler'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='sent_to',
            field=models.IntegerField(default=0, verbose_name='Iberilenler'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='success_count',
            field=models.IntegerField(default=0, verbose_name='Ýetenýeterler'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Başlyk'),
        ),
    ]
