# Generated by Django 5.2.8 on 2025-12-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_tokens', '0003_devicetoken_last_active_useractivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetoken',
            name='last_active',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Soňky açyş'),
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
