# Generated by Django 5.2.8 on 2025-12-28 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_tokens', '0004_alter_devicetoken_last_active_delete_useractivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicetoken',
            name='last_active',
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('app_open', 'Programma açdy'), ('view_announcement', 'Bildiriş gördi'), ('search', 'Gözleg etdi'), ('other', 'Başga')], default='app_open', max_length=50, verbose_name='Hereket görnüşi')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Goşmaça maglumat')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Haçan boldy')),
                ('device_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='device_tokens.devicetoken', verbose_name='Enjam tokeni')),
            ],
            options={
                'verbose_name': 'Ulanyjy hereketi',
                'verbose_name_plural': 'Ulanyjy hereketleri',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'device_token'], name='device_toke_created_63f9ee_idx'), models.Index(fields=['created_at'], name='device_toke_created_e16e3a_idx')],
            },
        ),
    ]
