# Generated by Django 5.2.8 on 2026-01-02 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_tokens', '0005_remove_devicetoken_last_active_useractivity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
