# Generated by Django 5.2.8 on 2025-11-28 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcement_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='photo',
        ),
    ]
