# Generated by Django 5.2.8 on 2025-12-03 05:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_remove_announcement_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['order_number', '-created_at']},
        ),
        migrations.AddField(
            model_name='announcement',
            name='order_number',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='announcement',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '+99312345678' (+993 followed by 8 digits)", regex='^\\+993\\d{8}$')]),
        ),
    ]
