# Generated by Django 5.2.8 on 2025-12-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_alter_announcement_options_announcement_order_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={},
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='order_number',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
