# Generated by Django 5.2.8 on 2025-12-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0005_alter_announcement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Enter 8 digits (country code +993 will be added automatically)', max_length=20, null=True),
        ),
    ]
