# Generated by Django 5.2.8 on 2025-12-03 05:39

from django.db import migrations, models
from datetime import datetime


def generate_unique_ids(apps, schema_editor):
    """Generate unique IDs for existing announcements"""
    Announcement = apps.get_model('announcements', 'Announcement')
    announcements = Announcement.objects.all().order_by('created_at')
    
    for idx, announcement in enumerate(announcements, start=1):
        date_str = announcement.created_at.strftime('%Y%m%d')
        announcement.unique_id = f'ANN-{date_str}-{idx:04d}'
        announcement.save()


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0006_alter_announcement_phone_number'),
    ]

    operations = [
        # Step 1: Add the field as nullable first
        migrations.AddField(
            model_name='announcement',
            name='unique_id',
            field=models.CharField(blank=True, editable=False, help_text='Auto-generated unique ID', max_length=20, null=True),
        ),
        # Step 2: Populate the field
        migrations.RunPython(generate_unique_ids, migrations.RunPython.noop),
        # Step 3: Make the field unique and non-nullable
        migrations.AlterField(
            model_name='announcement',
            name='unique_id',
            field=models.CharField(blank=True, editable=False, help_text='Auto-generated unique ID', max_length=20, unique=True),
        ),
    ]
