# Generated by Django 5.2.8 on 2025-12-03 05:41

from django.db import migrations


def simplify_unique_ids(apps, schema_editor):
    """Convert unique IDs to simple sequential numbers"""
    Announcement = apps.get_model('announcements', 'Announcement')
    announcements = Announcement.objects.all().order_by('id')
    
    for idx, announcement in enumerate(announcements, start=1):
        announcement.unique_id = str(idx)
        announcement.save()


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0007_add_unique_id_field'),
    ]

    operations = [
        migrations.RunPython(simplify_unique_ids, migrations.RunPython.noop),
    ]
