# Generated by Django 5.2.8 on 2025-12-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0008_simplify_unique_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='priority',
            field=models.IntegerField(default=0, help_text='Lower number = higher priority (0 is default)'),
        ),
    ]
