# Generated by Django 5.2.8 on 2025-12-03 06:01

from django.db import migrations, models


def fix_negative_priorities(apps, schema_editor):
    """Convert any negative priority values to 0"""
    Announcement = apps.get_model('announcements', 'Announcement')
    Announcement.objects.filter(priority__lt=0).update(priority=0)


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0009_announcement_priority'),
    ]

    operations = [
        # Step 1: Fix any negative values
        migrations.RunPython(fix_negative_priorities, migrations.RunPython.noop),
        # Step 2: Change field to PositiveIntegerField
        migrations.AlterField(
            model_name='announcement',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='0 = No priority, 1 = Highest priority, 2 = Second highest, etc.'),
        ),
    ]
