# Generated by Django 5.2.8 on 2025-12-11 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0012_pendingedit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementPendingEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('expiration_date', models.DateField()),
                ('status', models.CharField(choices=[('waiting_approval', 'Waiting Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='waiting_approval', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcements.category')),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_announcements', to=settings.AUTH_USER_MODEL)),
                ('original_announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_edits', to='announcements.announcement')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_edits', to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcements.village')),
            ],
        ),
        migrations.CreateModel(
            name='PendingEditPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='announcements/pending/')),
                ('pending_edit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='announcements.announcementpendingedit')),
            ],
        ),
        migrations.DeleteModel(
            name='PendingEdit',
        ),
    ]
