# Generated by Django 5.2.8 on 2025-12-12 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0013_announcementpendingedit_pendingeditphoto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingeditphoto',
            name='pending_edit',
        ),
        migrations.CreateModel(
            name='PendingAnnouncementEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('expiration_date', models.DateField()),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcements.category')),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_edits', to=settings.AUTH_USER_MODEL)),
                ('original_announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_edits', to='announcements.announcement')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcements.village')),
            ],
        ),
        migrations.CreateModel(
            name='PendingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='announcements/pending/')),
                ('pending_edit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_photos', to='announcements.pendingannouncementedit')),
            ],
        ),
        migrations.DeleteModel(
            name='AnnouncementPendingEdit',
        ),
        migrations.DeleteModel(
            name='PendingEditPhoto',
        ),
    ]
