# Generated by Django 5.2.8 on 2025-12-12 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0014_remove_pendingeditphoto_pending_edit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='status',
        ),
        migrations.CreateModel(
            name='PendingAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('expiration_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcements.category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_announcements', to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcements.village')),
            ],
        ),
        migrations.CreateModel(
            name='PendingAnnouncementPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='announcements/pending/')),
                ('pending_announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_photos', to='announcements.pendingannouncement')),
            ],
        ),
    ]
