# Generated by Django 5.2.8 on 2025-12-13 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0015_remove_announcement_status_pendingannouncement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='unique_id',
        ),
    ]
