# Generated by Django 5.2.8 on 2025-12-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0016_remove_announcement_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingannouncement',
            name='message_to_admin',
            field=models.TextField(blank=True, help_text="Manager's message to admin explaining the reason for this announcement"),
        ),
        migrations.AddField(
            model_name='pendingannouncementedit',
            name='message_to_admin',
            field=models.TextField(blank=True, help_text="Manager's message to admin explaining the reason for this edit"),
        ),
    ]
