# Generated by Django 5.2.8 on 2025-12-17 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0017_pendingannouncement_message_to_admin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pendingannouncement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pending Announcement', 'verbose_name_plural': 'Pending Announcements'},
        ),
        migrations.AlterModelOptions(
            name='pendingannouncementedit',
            options={'ordering': ['-edited_at'], 'verbose_name': 'Pending Announcement Edit', 'verbose_name_plural': 'Pending Announcement Edits'},
        ),
    ]
