# Generated by Django 5.2.8 on 2025-12-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0018_alter_pendingannouncement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('not_active', 'Not Active'), ('expired', 'Expired')], default='active', help_text='Active announcements are visible on frontend', max_length=20),
        ),
    ]
