# Generated by Django 5.2.8 on 2025-12-21 04:17

import announcements.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0019_announcement_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name': 'Bildiriş', 'verbose_name_plural': 'Bildirişler'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Bölüm', 'verbose_name_plural': 'Bölümler'},
        ),
        migrations.AlterModelOptions(
            name='village',
            options={'verbose_name': 'Ýer', 'verbose_name_plural': 'Ýerler'},
        ),
        migrations.AlterField(
            model_name='announcement',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Haçan tassyklandy'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_announcements', to=settings.AUTH_USER_MODEL, verbose_name='Kim tassyklady'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcements.category', verbose_name='Bölüm'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Haçan goşuldy'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL, verbose_name='Kim goşdy'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='description',
            field=models.TextField(verbose_name='Düşündiriş'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expiration_date',
            field=models.DateField(verbose_name='Möhleti'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Bildiriş'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Diňe 8 san giriziň. Ýurt kody +993 awtomatiki goşular.', max_length=20, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='0 = Ileri tutma ýok, 1 = Iň ýokary, 2 = Ikinji, we ş.m.', verbose_name='Ileri tutma'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('not_active', 'Not Active'), ('expired', 'Expired')], default='active', help_text='Işjeň bildirişler frontend-de görkezilýär', max_length=20, verbose_name='Ýagdaý'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Haçan üýtgedildi'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcements.village', verbose_name='Ýer'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='At'),
        ),
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(upload_to='categories/', verbose_name='Surat'),
        ),
        migrations.AlterField(
            model_name='pendingannouncement',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcements.category', verbose_name='Bölüm'),
        ),
        migrations.AlterField(
            model_name='pendingannouncement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Haçan goşuldy'),
        ),
        migrations.AlterField(
            model_name='pendingannouncement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_announcements', to=settings.AUTH_USER_MODEL, verbose_name='Kim goşdy'),
        ),
        migrations.AlterField(
            model_name='pendingannouncement',
            name='description',
            field=models.TextField(verbose_name='Düşündiriş'),
        ),
        migrations.AlterField(
            model_name='pendingannouncement',
            name='expiration_date',
            field=models.DateField(verbose_name='Möhleti'),
        ),
        migrations.AlterField(
            model_name='pendingannouncement',
            name='message_to_admin',
            field=models.TextField(blank=True, help_text='Bu bildirişiň sebäbini düşündiriň', verbose_name='Administratora habar'),
        ),
        migrations.AlterField(
            model_name='pendingannouncement',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Bildiriş'),
        ),
        migrations.AlterField(
            model_name='pendingannouncement',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='pendingannouncement',
            name='priority',
            field=models.PositiveIntegerField(default=0, verbose_name='Ileri tutma'),
        ),
        migrations.AlterField(
            model_name='pendingannouncement',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcements.village', verbose_name='Ýer'),
        ),
        migrations.AlterField(
            model_name='pendingannouncementedit',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcements.category', verbose_name='Bölüm'),
        ),
        migrations.AlterField(
            model_name='pendingannouncementedit',
            name='description',
            field=models.TextField(verbose_name='Düşündiriş'),
        ),
        migrations.AlterField(
            model_name='pendingannouncementedit',
            name='edited_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Haçan üýtgedildi'),
        ),
        migrations.AlterField(
            model_name='pendingannouncementedit',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_edits', to=settings.AUTH_USER_MODEL, verbose_name='Kim üýtgetdi'),
        ),
        migrations.AlterField(
            model_name='pendingannouncementedit',
            name='expiration_date',
            field=models.DateField(verbose_name='Möhleti'),
        ),
        migrations.AlterField(
            model_name='pendingannouncementedit',
            name='message_to_admin',
            field=models.TextField(blank=True, help_text='Bu üýtgetmeleriň sebäbini düşündiriň', verbose_name='Administratora habar'),
        ),
        migrations.AlterField(
            model_name='pendingannouncementedit',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Bildiriş'),
        ),
        migrations.AlterField(
            model_name='pendingannouncementedit',
            name='original_announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_edits', to='announcements.announcement', verbose_name='Asyl bildiriş'),
        ),
        migrations.AlterField(
            model_name='pendingannouncementedit',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='pendingannouncementedit',
            name='priority',
            field=models.PositiveIntegerField(default=0, verbose_name='Ileri tutma'),
        ),
        migrations.AlterField(
            model_name='pendingannouncementedit',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcements.village', verbose_name='Ýer'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=announcements.models.announcement_image_path),
        ),
        migrations.AlterField(
            model_name='village',
            name='name',
            field=models.CharField(max_length=100, verbose_name='At'),
        ),
    ]
