# Generated by Django 5.2.8 on 2025-12-21 04:19

import announcements.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0020_alter_announcement_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Banner', 'verbose_name_plural': 'Bannerler'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Saýlanan', 'verbose_name_plural': 'Saýlananlar'},
        ),
        migrations.AlterModelOptions(
            name='pendingannouncement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Garaşylýan bildiriş', 'verbose_name_plural': 'Garaşylýan bildirişler'},
        ),
        migrations.AlterModelOptions(
            name='pendingannouncementedit',
            options={'ordering': ['-edited_at'], 'verbose_name': 'Garaşylýan üýtgetme', 'verbose_name_plural': 'Garaşylýan üýtgetmeler'},
        ),
        migrations.AlterModelOptions(
            name='pendingannouncementphoto',
            options={'verbose_name': 'Garaşylýan bildirişiň suraty', 'verbose_name_plural': 'Garaşylýan bildirişiň suratlary'},
        ),
        migrations.AlterModelOptions(
            name='pendingphoto',
            options={'verbose_name': 'Garaşylýan üýtgetmeniň suraty', 'verbose_name_plural': 'Garaşylýan üýtgetmeniň suratlary'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Surat', 'verbose_name_plural': 'Suratlar'},
        ),
        migrations.AlterField(
            model_name='banner',
            name='announcement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='announcements.announcement', verbose_name='Bildiriş'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='photo',
            field=models.ImageField(upload_to='banners/', verbose_name='Surat'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcements.announcement', verbose_name='Bildiriş'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='device_token',
            field=models.CharField(max_length=255, verbose_name='Enjam tokeni'),
        ),
        migrations.AlterField(
            model_name='pendingannouncementphoto',
            name='image',
            field=models.ImageField(upload_to='announcements/pending/', verbose_name='Surat'),
        ),
        migrations.AlterField(
            model_name='pendingannouncementphoto',
            name='pending_announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_photos', to='announcements.pendingannouncement', verbose_name='Garaşylýan bildiriş'),
        ),
        migrations.AlterField(
            model_name='pendingphoto',
            name='image',
            field=models.ImageField(upload_to='announcements/pending/', verbose_name='Surat'),
        ),
        migrations.AlterField(
            model_name='pendingphoto',
            name='pending_edit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_photos', to='announcements.pendingannouncementedit', verbose_name='Garaşylýan üýtgetme'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='announcements.announcement', verbose_name='Bildiriş'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=announcements.models.announcement_image_path, verbose_name='Surat'),
        ),
    ]
