# Generated by Django 5.2.8 on 2025-12-27 18:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0021_alter_banner_options_alter_favorite_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Haçan goşuldy'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expiration_date',
            field=models.DateField(db_index=True, verbose_name='Möhleti'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='priority',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='0 = Ileri tutma ýok, 1 = Iň ýokary, 2 = Ikinji, we ş.m.', verbose_name='Ileri tutma'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('not_active', 'Not Active'), ('expired', 'Expired')], db_index=True, default='active', help_text='Işjeň bildirişler frontend-de görkezilýär', max_length=20, verbose_name='Ýagdaý'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='device_token',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Enjam tokeni'),
        ),
        migrations.AlterField(
            model_name='pendingannouncement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Haçan goşuldy'),
        ),
        migrations.AlterField(
            model_name='pendingannouncementedit',
            name='edited_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Haçan üýtgedildi'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['status', '-priority', '-created_at'], name='ann_status_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['status', 'category', '-created_at'], name='ann_status_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['expiration_date', 'status'], name='ann_exp_status_idx'),
        ),
    ]
